
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label Calculadora;

	private global::Gtk.Entry Pantalla;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button Butreset;

	private global::Gtk.Button ButC;

	private global::Gtk.HBox hbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button But7;

	private global::Gtk.Button But8;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button But9;

	private global::Gtk.Button Butdivision;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox5;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button But4;

	private global::Gtk.Button But5;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button But6;

	private global::Gtk.Button Butmult;

	private global::Gtk.HBox hbox8;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Button But1;

	private global::Gtk.Button But2;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button But3;

	private global::Gtk.Button Butresta;

	private global::Gtk.HBox hbox11;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Button Butpunto;

	private global::Gtk.Button But;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button Butigual;

	private global::Gtk.Button Butmas;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(30));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.Calculadora = new global::Gtk.Label();
		this.Calculadora.Name = "Calculadora";
		this.Calculadora.LabelProp = global::Mono.Unix.Catalog.GetString("Calculadora");
		this.vbox2.Add(this.Calculadora);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.Calculadora]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.Pantalla = new global::Gtk.Entry();
		this.Pantalla.CanFocus = true;
		this.Pantalla.Name = "Pantalla";
		this.Pantalla.IsEditable = false;
		this.Pantalla.InvisibleChar = '•';
		this.vbox2.Add(this.Pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.Pantalla]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Butreset = new global::Gtk.Button();
		this.Butreset.WidthRequest = 115;
		this.Butreset.CanFocus = true;
		this.Butreset.Name = "Butreset";
		this.Butreset.UseUnderline = true;
		this.Butreset.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.hbox1.Add(this.Butreset);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Butreset]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.ButC = new global::Gtk.Button();
		this.ButC.WidthRequest = 37;
		this.ButC.HeightRequest = 35;
		this.ButC.CanFocus = true;
		this.ButC.Name = "ButC";
		this.ButC.UseUnderline = true;
		this.ButC.Label = global::Mono.Unix.Catalog.GetString("C");
		this.hbox1.Add(this.ButC);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.ButC]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.But7 = new global::Gtk.Button();
		this.But7.WidthRequest = 35;
		this.But7.HeightRequest = 35;
		this.But7.CanFocus = true;
		this.But7.Name = "But7";
		this.But7.UseUnderline = true;
		this.But7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox3.Add(this.But7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.But7]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.But8 = new global::Gtk.Button();
		this.But8.WidthRequest = 35;
		this.But8.HeightRequest = 35;
		this.But8.CanFocus = true;
		this.But8.Name = "But8";
		this.But8.UseUnderline = true;
		this.But8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox3.Add(this.But8);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.But8]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.But9 = new global::Gtk.Button();
		this.But9.WidthRequest = 35;
		this.But9.HeightRequest = 35;
		this.But9.CanFocus = true;
		this.But9.Name = "But9";
		this.But9.UseUnderline = true;
		this.But9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox4.Add(this.But9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.But9]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Butdivision = new global::Gtk.Button();
		this.Butdivision.WidthRequest = 35;
		this.Butdivision.HeightRequest = 35;
		this.Butdivision.CanFocus = true;
		this.Butdivision.Name = "Butdivision";
		this.Butdivision.UseUnderline = true;
		this.Butdivision.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox4.Add(this.Butdivision);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Butdivision]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox4]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.But4 = new global::Gtk.Button();
		this.But4.WidthRequest = 35;
		this.But4.HeightRequest = 35;
		this.But4.CanFocus = true;
		this.But4.Name = "But4";
		this.But4.UseUnderline = true;
		this.But4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox6.Add(this.But4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.But4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.But5 = new global::Gtk.Button();
		this.But5.WidthRequest = 35;
		this.But5.HeightRequest = 35;
		this.But5.CanFocus = true;
		this.But5.Name = "But5";
		this.But5.UseUnderline = true;
		this.But5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox6.Add(this.But5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.But5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox5.Add(this.hbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.But6 = new global::Gtk.Button();
		this.But6.WidthRequest = 35;
		this.But6.HeightRequest = 35;
		this.But6.CanFocus = true;
		this.But6.Name = "But6";
		this.But6.UseUnderline = true;
		this.But6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox7.Add(this.But6);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.But6]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Butmult = new global::Gtk.Button();
		this.Butmult.WidthRequest = 35;
		this.Butmult.HeightRequest = 35;
		this.Butmult.CanFocus = true;
		this.Butmult.Name = "Butmult";
		this.Butmult.UseUnderline = true;
		this.Butmult.Label = global::Mono.Unix.Catalog.GetString("*");
		this.hbox7.Add(this.Butmult);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Butmult]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox5.Add(this.hbox7);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox7]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.But1 = new global::Gtk.Button();
		this.But1.WidthRequest = 35;
		this.But1.HeightRequest = 35;
		this.But1.CanFocus = true;
		this.But1.Name = "But1";
		this.But1.UseUnderline = true;
		this.But1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox9.Add(this.But1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.But1]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.But2 = new global::Gtk.Button();
		this.But2.WidthRequest = 35;
		this.But2.HeightRequest = 35;
		this.But2.CanFocus = true;
		this.But2.Name = "But2";
		this.But2.UseUnderline = true;
		this.But2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox9.Add(this.But2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.But2]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.hbox8.Add(this.hbox9);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox9]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.But3 = new global::Gtk.Button();
		this.But3.WidthRequest = 35;
		this.But3.HeightRequest = 35;
		this.But3.CanFocus = true;
		this.But3.Name = "But3";
		this.But3.UseUnderline = true;
		this.But3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox10.Add(this.But3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.But3]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.Butresta = new global::Gtk.Button();
		this.Butresta.WidthRequest = 35;
		this.Butresta.HeightRequest = 35;
		this.Butresta.CanFocus = true;
		this.Butresta.Name = "Butresta";
		this.Butresta.UseUnderline = true;
		this.Butresta.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox10.Add(this.Butresta);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.Butresta]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		this.hbox8.Add(this.hbox10);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox10]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox4.Add(this.hbox8);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.Butpunto = new global::Gtk.Button();
		this.Butpunto.WidthRequest = 35;
		this.Butpunto.HeightRequest = 35;
		this.Butpunto.CanFocus = true;
		this.Butpunto.Name = "Butpunto";
		this.Butpunto.UseUnderline = true;
		this.Butpunto.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox12.Add(this.Butpunto);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.Butpunto]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.But = new global::Gtk.Button();
		this.But.WidthRequest = 35;
		this.But.HeightRequest = 35;
		this.But.CanFocus = true;
		this.But.Name = "But";
		this.But.UseUnderline = true;
		this.But.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox12.Add(this.But);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.But]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.hbox11.Add(this.hbox12);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox12]));
		w31.Position = 0;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.Butigual = new global::Gtk.Button();
		this.Butigual.WidthRequest = 35;
		this.Butigual.HeightRequest = 35;
		this.Butigual.CanFocus = true;
		this.Butigual.Name = "Butigual";
		this.Butigual.UseUnderline = true;
		this.Butigual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox13.Add(this.Butigual);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.Butigual]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.Butmas = new global::Gtk.Button();
		this.Butmas.WidthRequest = 35;
		this.Butmas.HeightRequest = 35;
		this.Butmas.CanFocus = true;
		this.Butmas.Name = "Butmas";
		this.Butmas.UseUnderline = true;
		this.Butmas.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox13.Add(this.Butmas);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.Butmas]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.hbox11.Add(this.hbox13);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox13]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		this.vbox4.Add(this.hbox11);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox11]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 220;
		this.DefaultHeight = 315;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Butreset.Clicked += new global::System.EventHandler(this.OnClickedReset);
		this.ButC.Clicked += new global::System.EventHandler(this.OnClickedC);
		this.But7.Clicked += new global::System.EventHandler(this.OnClicked7);
		this.But8.Clicked += new global::System.EventHandler(this.OnClicked8);
		this.But9.Clicked += new global::System.EventHandler(this.OnClicked9);
		this.Butdivision.Clicked += new global::System.EventHandler(this.OnClickedDivision);
		this.But4.Clicked += new global::System.EventHandler(this.OnClicked4);
		this.But5.Clicked += new global::System.EventHandler(this.OnClicked5);
		this.But6.Clicked += new global::System.EventHandler(this.OnClicked6);
		this.Butmult.Clicked += new global::System.EventHandler(this.OnClickedMulti);
		this.But1.Clicked += new global::System.EventHandler(this.OnClicked1);
		this.But2.Clicked += new global::System.EventHandler(this.OnClicked2);
		this.But3.Clicked += new global::System.EventHandler(this.OnClicked3);
		this.Butresta.Clicked += new global::System.EventHandler(this.OnClickedResta);
		this.Butpunto.Clicked += new global::System.EventHandler(this.OnClickedpunto);
		this.But.Clicked += new global::System.EventHandler(this.OnClicked0);
		this.Butigual.Clicked += new global::System.EventHandler(this.OnClickedIgual);
		this.Butmas.Clicked += new global::System.EventHandler(this.OnClickedSuma);
	}
}
