
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vBox;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label Texto;

	private global::Gtk.Button Aleatorio;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox = new global::Gtk.VBox();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		// Container child vBox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Texto = new global::Gtk.Label();
		this.Texto.Name = "Texto";
		this.Texto.LabelProp = global::Mono.Unix.Catalog.GetString("El numero");
		this.hbox5.Add(this.Texto);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Texto]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Aleatorio = new global::Gtk.Button();
		this.Aleatorio.CanFocus = true;
		this.Aleatorio.Name = "Aleatorio";
		this.Aleatorio.UseUnderline = true;
		this.Aleatorio.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.hbox5.Add(this.Aleatorio);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.Aleatorio]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vBox.Add(this.hbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox[this.hbox5]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
